# Use OpenJDK image from Java 21
FROM openjdk:21-jdk-slim

# Set working directory inside container
WORKDIR /app

# Copy the JAR file generated by Gradle build to the container
COPY build/libs/find_it-0.0.1-SNAPSHOT.jar app.jar

# Copy the keystore.p12 file into the container
COPY src/main/resources/keystore.p12 /app/config/keystore.p12

# Copy the Firebase configuration file
COPY firebaseworry.json /app/config/firebaseworry.json

# Expose the port used by the application in the container
EXPOSE 8080
EXPOSE 8443

# Set command to run JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]
