# Use OpenJDK image from Java 21
FROM openjdk:21-jdk-slim

# Set working directory inside container
WORKDIR /app

# Copy the JAR file generated by Gradle build to the container
COPY build/libs/find_it-0.0.1-SNAPSHOT.jar app.jar

# Copy the Firebase configuration file from the root directory of the project
COPY firebaseworry.json /app/config/firebaseworry.json

# Expose the port used by the application in the container
EXPOSE 8080

# Set command to run JAR file
ENTRYPOINT ["java", "-jar", "app.jar"]
