version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          cpus: "0.3" # Limit to 30% of one core
          memory: 512m # Limit memory to 512MB

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 12
      KAFKA_LOG_SEGMENT_BYTES: 67108864
      KAFKA_COMPRESSION_TYPE: gzip
    ports:
      - "9092:9092"
    deploy:
      resources:
        limits:
          cpus: "0.6" # Limit to 60% of one core
          memory: 1g # Limit memory to 1GB

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: SECRET-KEY
      SPRING_DATASOURCE_URL: jdbc:mysql://capstone.cbweg6cmcjxe.ap-northeast-2.rds.amazonaws.com:3306/capstone
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FCM_CERTIFICATION: /app/config/firebaseworry.json
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_CONSUMER_GROUP_ID: my-custom-group
    volumes:
      - ./firebaseworry.json:/app/config/firebaseworry.json
      - /home/ubuntu/logs:/logs
    depends_on:
      - kafka
    command: >
      sh -c "java -jar app.jar"
    deploy:
      resources:
        limits:
          cpus: "0.5" # Limit to 50% of one core
          memory: 2g # Limit memory to 1.5GB
