services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      SPRING_PROFILES_ACTIVE: SECRET-KEY
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:13306/capstone
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      FCM_CERTIFICATION: /app/config/firebaseworry.json
    volumes:
      - ./firebaseworry.json:/app/config/firebaseworry.json
