spring:
  profiles:
    active: SECRET-KEY
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://${database-host}/${database-name}
    url: jdbc:mysql://localhost:13306/capstone
    username: ${database-username}
    password: ${database-password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  logging.level:
    org.hibernate.SQL: debug

  # 파일 업로드 설정 추가
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Firebase 설정 추가
fcm:
  certification: firebaseworry.json

# OpenAI 설정
openai:
  model: gpt-4o
  api:
    url: "https://api.openai.com/v1/chat/completions"
    key: ${OPENAI_API_KEY}
