#spring:
#  profiles:
#    active: SECRET-KEY
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
##    url: jdbc:mysql://${database-host}/${database-name}
#    url: jdbc:mysql://localhost:13306/capstone

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${database-username}
    password: ${database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  logging.level:
    org.hibernate.SQL: debug
  # 파일 업로드 설정 추가
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# Firebase 설정 추가
fcm:
  certification: /app/config/firebaseworry.json

# OpenAI 설정
openai:
  model: gpt-4o
  api:
    url: "https://api.openai.com/v1/chat/completions"
    key: ${OPENAI_API_KEY}

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID:default-group} # 기본값 제공

