server:
  port: 8443
  ssl:
    key-store: /app/config/keystore.p12
    key-store-password: 1234 # 생성 시 입력한 비밀번호
    key-store-type: PKCS12

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  datasource:
    url: ${SPRING_DATASOURCE_URL}?serverTimezone=Asia/Seoul
    username: ${database-username}
    password: ${database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    file:
      name: /logs/spring-boot.log
    level:
      org.hibernate.SQL: info
      org.apache.kafka: warn
      org.springframework.kafka: warn
  jackson:
    time-zone: Asia/Seoul

# File upload configuration
spring.servlet.multipart:
  enabled: true
  max-file-size: 10MB
  max-request-size: 10MB

# Firebase configuration
fcm:
  certification: /app/config/firebaseworry.json

# OpenAI configuration
openai:
  model: gpt-4o
  api:
    url: "https://api.openai.com/v1/chat/completions"
    key: ${OPENAI_API_KEY}

# Kafka configuration
kafka:
  bootstrap-servers: kafka:29092
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID}
    auto-offset-reset: earliest
    enable-auto-commit: true
    max-poll-records: 10
    properties:
      fetch.min.bytes: 1
      fetch.max.wait.ms: 500
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      retries: 3
      batch.size: 16384
      linger.ms: 1
      compression.type: snappy

# Kafka Listener
spring.kafka.listener:
  ack-mode: batch

aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  region: ap-northeast-2
  s3:
    bucket: capstonem
    folder: uploads
