spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE} # 프로파일 설정
  datasource:
    url: ${SPRING_DATASOURCE_URL}?serverTimezone=Asia/Seoul
    username: ${database-username}
    password: ${database-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  logging:
    file:
      name: /logs/spring-boot.log
    level:
      org.hibernate.SQL: info
      org.apache.kafka: warn  # Kafka 관련 로그를 WARN으로 설정
      org.springframework.kafka: warn
  jackson:
    time-zone: Asia/Seoul

# 파일 업로드 설정
spring.servlet.multipart:
  enabled: true
  max-file-size: 10MB
  max-request-size: 10MB

# Firebase 설정
fcm:
  certification: /app/config/firebaseworry.json

# OpenAI 설정
openai:
  model: gpt-4o
  api:
    url: "https://api.openai.com/v1/chat/completions"
    key: ${OPENAI_API_KEY}

# Kafka 설정
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  consumer:
    group-id: ${KAFKA_CONSUMER_GROUP_ID}
    auto-offset-reset: earliest
    enable-auto-commit: true
    max-poll-records: 10 # 한 번에 처리할 메시지 수 제한 (최적화)
    properties:
      fetch.min.bytes: 1 # 최소 데이터 크기 (바이트 단위)
      fetch.max.wait.ms: 500 # 최대 대기 시간 (밀리초 단위)
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      retries: 3 # 실패 시 재시도 횟수
      batch.size: 16384 # 배치 크기 (16KB)
      linger.ms: 1 # 배치 전송 지연 시간
      compression.type: snappy # 메시지 압축 방식

# Kafka Listener
spring.kafka.listener:
  ack-mode: batch # 배치 단위로 메시지 확인

